"""add table args in users

Revision ID: 1da6dd16ae32
Revises: 8d4176ed511a
Create Date: 2026-07-01 17:54:33.935199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da6dd16ae32'
down_revision: Union[str, Sequence[str], None] = '8d4176ed511a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_user_name_key'), 'users', type_='unique')
    op.create_unique_constraint('un_users_email', 'users', ['email'])
    op.create_unique_constraint('un_users_user_name', 'users', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('un_users_user_name', 'users', type_='unique')
    op.drop_constraint('un_users_email', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_user_name_key'), 'users', ['user_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
