"""add cascade deletion  rules for tables

Revision ID: 60b9604bf1ab
Revises: c75ba1931815
Create Date: 2026-07-14 12:40:52.033286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b9604bf1ab'
down_revision: Union[str, Sequence[str], None] = 'c75ba1931815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('projects_owner_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tasks_title_key'), 'tasks', type_='unique')
    op.create_unique_constraint('un_tasks_project_title', 'tasks', ['project_id', 'title'])
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_project_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['worker_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_project_id_fkey'), 'tasks', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'])
    op.drop_constraint('un_tasks_project_title', 'tasks', type_='unique')
    op.create_unique_constraint(op.f('tasks_title_key'), 'tasks', ['title'], postgresql_nulls_not_distinct=False)
    op.drop_column('tasks', 'worker_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_owner_id_fkey'), 'projects', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
