"""add fields is_active, registration_date  into users table

Revision ID: 8d4176ed511a
Revises: 4fd16032b713
Create Date: 2026-06-27 15:44:59.722581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4176ed511a'
down_revision: Union[str, Sequence[str], None] = '4fd16032b713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_date')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
