"""add unique constraint in projects

Revision ID: c75ba1931815
Revises: 90c0587b5c17
Create Date: 2026-07-08 12:52:51.931817

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c75ba1931815"
down_revision: Union[str, Sequence[str], None] = "90c0587b5c17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("projects_title_key"), "projects", type_="unique")
    op.create_unique_constraint("un_projects_title", "projects", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("un_projects_title", "projects", type_="unique")
    op.create_unique_constraint(
        op.f("projects_title_key"),
        "projects",
        ["title"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
